#!/bin/bash
if type git >> /dev/null; then
  repo="miyabisun/dotfiles"
  git clone "https://github.com/${repo}.git" ~/.dotfiles
  git -C ~/.dotfiles remote set-url origin "git@github.com:${repo}.git"
  bash ~/.dotfiles/bin/install
else
  echo "not found git."
fi
