# Prompt: fish-like minimal
# If Powerlevel10k is not available, use a plain zsh prompt
if [[ -z "$POWERLEVEL9K_CONFIG_FILE" ]]; then
  setopt prompt_subst
  autoload -Uz vcs_info
  precmd() { vcs_info }
  zstyle ':vcs_info:git:*' formats ' (%b)'
  PROMPT='%F{yellow}%m%f %F{green}%~%f%F{white}${vcs_info_msg_0_}%f%(?.%F{green}.%F{red}) $%f '
  RPROMPT=''
  return
fi

# Powerlevel10k overrides
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs prompt_char)

# Context: hostname in yellow
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO,ROOT,REMOTE,REMOTE_SUDO}_BACKGROUND='none'
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO,ROOT,REMOTE,REMOTE_SUDO}_FOREGROUND='white'
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO,ROOT,REMOTE,REMOTE_SUDO}_CONTENT_EXPANSION='%F{yellow}%m '
typeset -g POWERLEVEL9K_CONTEXT_LEFT_{LEFT,RIGHT}_WHITESPACE=
typeset -g POWERLEVEL9K_CONTEXT_RIGHT_{LEFT,RIGHT}_WHITESPACE=
typeset -g POWERLEVEL9K_CONTEXT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

# Remove powerline separators and background fills
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''

# Dir: no background, green text
typeset -g POWERLEVEL9K_DIR_BACKGROUND='none'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='green'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='green'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='green'
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=false
typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND='none'
typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND='green'
typeset -g POWERLEVEL9K_DIR_NON_EXISTENT_BACKGROUND='none'
typeset -g POWERLEVEL9K_DIR_NON_EXISTENT_FOREGROUND='green'
typeset -g POWERLEVEL9K_DIR_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_LEFT_{LEFT,RIGHT}_WHITESPACE=
typeset -g POWERLEVEL9K_DIR_RIGHT_{LEFT,RIGHT}_WHITESPACE=

# VCS: show branch name only like fish — (master)
typeset -g POWERLEVEL9K_VCS_{CLEAN,MODIFIED,UNTRACKED,CONFLICTED,LOADING}_BACKGROUND='none'
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,LOADING}_FOREGROUND='white'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='red'
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=''
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='%F{white} (${VCS_STATUS_LOCAL_BRANCH:-${VCS_STATUS_COMMIT[1,8]}})'
typeset -g POWERLEVEL9K_VCS_LEFT_{LEFT,RIGHT}_WHITESPACE=
typeset -g POWERLEVEL9K_VCS_RIGHT_{LEFT,RIGHT}_WHITESPACE=

# Prompt char: $ (green=ok, red=error)
typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND='none'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION=' $'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION=' $'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION=' $'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION=' $'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='green'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='red'
